const getAgentScript = (agent) => {
  return `bun run src/agents/${agent}.ts`;
};

const commonEnv = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  FALKORDB_HOST: process.env.FALKORDB_HOST || 'localhost',
  FALKORDB_PORT: process.env.FALKORDB_PORT || '6379',
  FALKORDB_USERNAME: process.env.FALKORDB_USERNAME || 'falkordb',
  FALKORDB_PASSWORD: process.env.FALKORDB_PASSWORD || '',
  SQLITE_EVENTS_PATH: process.env.SQLITE_EVENTS_PATH || './solaris-events.db',
  OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
  OLLAMA_ENABLED: process.env.OLLAMA_ENABLED || 'true',
};

const configs = [
  {
    name: 'commander',
    script: getAgentScript('commander'),
    env: { AGENT_ROLE: 'commander', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '500M',
    instance_var: 'INSTANCE_ID',
  },
  {
    name: 'verifier',
    script: getAgentScript('verifier'),
    env: { AGENT_ROLE: 'verifier', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '200M',
    instance_var: 'INSTANCE_ID',
  },
  {
    name: 'mcp-server',
    script: 'bun run src/mcp/server.ts',
    env: { AGENT_ROLE: 'mcp-server', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    instance_var: 'INSTANCE_ID',
  },
  {
    name: 'gamma-1',
    script: getAgentScript('gamma'),
    env: { AGENT_ROLE: 'gamma', INSTANCE_ID: '1', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '2G',
    instance_var: 'INSTANCE_ID',
  },
  {
    name: 'alpha-recon',
    script: getAgentScript('alpha-recon'),
    env: { AGENT_ROLE: 'alpha', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '2G',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'osint',
    script: getAgentScript('osint'),
    env: { AGENT_ROLE: 'osint', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'mission-planner',
    script: getAgentScript('mission-planner'),
    env: { AGENT_ROLE: 'mission_planner', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'chain-planner',
    script: getAgentScript('chain-planner'),
    env: { AGENT_ROLE: 'chain_planner', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'critic',
    script: getAgentScript('critic'),
    env: { AGENT_ROLE: 'critic', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '500M',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'post-exploit',
    script: getAgentScript('post-exploit'),
    env: { AGENT_ROLE: 'post_exploit', ...commonEnv },
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    instance_var: 'INSTANCE_ID',
    restart_delay: 4000,
  },
  {
    name: 'report-agent',
    script: getAgentScript('report-agent'),
    env: { AGENT_ROLE: 'report_agent', ...commonEnv },
    autorestart: false,
    watch: false,
    max_memory_restart: '2G',
    instance_var: 'INSTANCE_ID',
  },
];

module.exports = configs;
